version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "ap-southeast-2"
    HUGO_VERSION: "0.73.0"
    HUGO_SHA256: "7238b1b39d50667190020c93370bb2727d9097226cb3147c982d4d40004da09f"

phases:
  build:
    commands:
      - hugo --minify --verbose --cleanDestinationDir

  post_build:
    commands:
      - aws s3 sync --region=ap-southeast-2 --acl public-read --delete public s3://mojain.com.au/ --cache-control max-age=3600
      - aws cloudfront create-invalidation --distribution-id E2QM00W7R0PR64 --paths /index.html /index.xml
